### ISSUE TITLE
Indentation is not working in code string

### ISSUE THREAD

**Issue by AsAddict** [purcell/mmm-mode#87]
![image](https://user-images.githubusercontent.com/6167357/41200961-43aa27d0-6ce1-11e8-976c-dfc6164e6be0.png)

I would like to enable mmm-mode in the code string. the syntax-highlight looks correct but indentation not working... did I miss something?

thanks!!!

**Comment by purcell** [comment]
What steps would someone need to follow to reproduce this? It looks like you have some sort of custom MMM configuration.

**Comment by AsAddict** [comment]
Hi purcell :), my config is very basic here:


  
```emacs-lisp
(require 'mmm-mode)
(setq mmm-global-mode 'maybe)

(mmm-add-classes
 '((cljs-glsl
    :submode js-mode
    :front "^<begin-shader>[\n\r]+"
    :back "^<end-shader>$")))

(mmm-add-mode-ext-class 'clojurescript-mode nil 'cljs-glsl)
```
And I have test it with more detail, and I guess u may find what the problem there:

```clojure
<begin-shader>

void main() {
    // identation is ok!
}

<end-shader>

;; ' (<-- the single quote makes the code following not working for the indentation....)

<begin-shader>

void main() {
// cant indent...    
}

<end-shader>

;; ' 

<begin-shader>

void main() {
    // identation is ok !
}

<end-shader>

;; "
<begin-shader>

void main() {
// cant indent
}

<end-shader>

;; "
<begin-shader>

void main() {
    // indentatio is ok!
}

<end-shader>

```

**Comment by dgutov** [comment]
First of all, please update to the latest master (I just pushed a fix for `mmm-indent-line-narrowed`). Then try one of these:

```el
(setq mmm-indent-line-function #'mmm-indent-line-narrowed)
```

or 

```el
(setq indent-line-function #'mmm-indent-line-narrowed)
```

One should work, depending on where you put this line.

**Comment by AsAddict** [comment]
thanks dgutov!
May I ask how can I install the latest one? do I need to install manually since the elpa doesn't have any update there ?

**Comment by dgutov** [comment]
Err, okay, I'll push a new version.

Kinda got used to this being in MELPA.

**Comment by AsAddict** [comment]
thank so much! 👍

**Comment by dgutov** [comment]
I've pushed the new version now. It should get released within 24 hours.

**Comment by AsAddict** [comment]
thanks dgutov!
but, after installed the latest release, It's still not working... do I need some more configuration or something ?

**Comment by dgutov** [comment]
Yes, you do. I mentioned it above.
